version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    container_name: keycloak
